# Generated by Django 4.2.27 on 2026-01-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='disponibilidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido')], db_column='disponibilidad', default='Disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateField(blank=True, db_column='fecha_publicacion', null=True),
        ),
    ]
