# Generated by Django 4.2.27 on 2026-01-28 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0002_ventagarage_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='rutaimagen',
            field=models.URLField(blank=True, db_column='rutaimagen', null=True),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='totalhoras',
            field=models.IntegerField(blank=True, db_column='totalhoras', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(blank=True, db_column='valordelbien', decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
