# Generated by Django 4.2.27 on 2026-01-26 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_datospersonales_foto_perfil_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilidadSecciones',
            fields=[
                ('idvisibilidad', models.AutoField(db_column='idvisibilidad', primary_key=True, serialize=False)),
                ('mostrar_experiencia_laboral', models.BooleanField(db_column='mostrar_experiencia_laboral', default=True)),
                ('mostrar_educacion_cursos', models.BooleanField(db_column='mostrar_educacion_cursos', default=True)),
                ('mostrar_reconocimientos', models.BooleanField(db_column='mostrar_reconocimientos', default=True)),
                ('mostrar_productos_academicos', models.BooleanField(db_column='mostrar_productos_academicos', default=True)),
                ('mostrar_productos_laborales', models.BooleanField(db_column='mostrar_productos_laborales', default=True)),
                ('mostrar_venta_garage', models.BooleanField(db_column='mostrar_venta_garage', default=True)),
                ('perfil', models.OneToOneField(db_column='idperfil', on_delete=django.db.models.deletion.CASCADE, related_name='visibilidad_secciones', to='perfil.datospersonales')),
            ],
            options={
                'db_table': 'VISIBILIDADSECCIONES',
            },
        ),
    ]
