# Generated by Django 4.2.27 on 2026-01-28 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_visibilidadsecciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visibilidadsecciones',
            options={'verbose_name': 'Check Box', 'verbose_name_plural': 'Check Box'},
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(db_column='perfilactivo', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
